apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8s-plex-data
spec:
  capacity:
    storage: 30Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: plex
    name: pvc-k8s-plex-data
  nfs:
    server: 172.16.15.11
    path: "/volume1/k8s-medias"
