apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8s-plex-transcode
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: plex
    name: pvc-k8s-plex-transcode
  nfs:
    server: 172.16.15.11
    path: "/volume1/k8s-plex-transcode"