apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s-plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
