apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: Synology-nfs
provisioner: kubernetes.io/nfs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate