apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admins-CRB
subjects:
- kind: Group
  name: kube-admins-virtucon@virtucon.local #AD Group Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin  # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io