apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-plex-transcode
  labels:
    name: k8s-plex-transcode # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.15.11 # ip addres of nfs server
    path: "/volume1/k8s-plex-transcode" # path to directory