apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ops
  name: operations-role
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["services", "endpoints", "pods", "pods/log", "configmaps", "deployments", "jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ops
  name: operations-RB
subjects:
- kind: Group
  name: kube-ops-virtucon # AD Group Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: operations-role # must match the name of the Role to bind to
  apiGroup: rbac.authorization.k8s.io