apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-plex-transcode
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.15.11
    path: "/volume1/k8s-plex-transcode"
